#!/bin/bash

rm -rf $1/priv-app/EngineerMode
rm -rf $1/product/app/CalendarGoogle
rm -rf $1/product/app/Chrome
rm -rf $1/product/app/DualApp
rm -rf $1/product/app/Gmail2
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/IWTMMI-0311
rm -rf $1/product/app/Maps
rm -rf $1/product/app/Messages
rm -rf $1/product/app/Photos
rm -rf $1/product/app/SecurityCom
rm -rf $1/product/app/YTMusic
rm -rf $1/product/app/YoParty
rm -rf $1/product/app/YouTube
rm -rf $1/product/app/factoryTest
rm -rf $1/product/app/talkback
rm -rf $1/product/operator/app/Boomplay
rm -rf $1/product/operator/app/Calendar
rm -rf $1/product/operator/app/Drive
rm -rf $1/product/operator/app/Duo
rm -rf $1/product/operator/app/FacebookFull
rm -rf $1/product/operator/app/TGraffiti
rm -rf $1/product/operator/app/Videos
rm -rf $1/product/operator/app/Welife
rm -rf $1/product/priv-app/ARCore
rm -rf $1/product/priv-app/AndroidAutoStub
rm -rf $1/product/priv-app/FilesGoogle
rm -rf $1/product/priv-app/Velvet
rm -rf $1/product/priv-app/Wellbeing
rm -rf $1/system_ext/app/AiGallery
rm -rf $1/system_ext/app/Browser
rm -rf $1/system_ext/app/Calculator
rm -rf $1/system_ext/app/ChildMode
rm -rf $1/system_ext/app/FacebookAppManager
rm -rf $1/system_ext/app/FacemojiKeyboard
rm -rf $1/system_ext/app/Health
rm -rf $1/system_ext/app/HiTranslate
rm -rf $1/system_ext/app/Hoffnung
rm -rf $1/system_ext/app/ManualGuide
rm -rf $1/system_ext/app/Phoenix
rm -rf $1/system_ext/app/Power
rm -rf $1/system_ext/app/SmartScanner
rm -rf $1/system_ext/app/SoundRecorder3RD
rm -rf $1/system_ext/app/TranssionCamera
rm -rf $1/system_ext/app/VideoPlayer
rm -rf $1/system_ext/app/Weather
rm -rf $1/system_ext/priv-app/AHAGames
rm -rf $1/system_ext/priv-app/AntiTheft
rm -rf $1/system_ext/priv-app/AppUpdate
rm -rf $1/system_ext/priv-app/Carlcare
rm -rf $1/system_ext/priv-app/FacebookServices
rm -rf $1/system_ext/priv-app/OOBE
rm -rf $1/system_ext/priv-app/PalmStore
rm -rf $1/system_ext/priv-app/TranAbe
rm -rf $1/system_ext/priv-app/Trancare
rm -rf $1/system_ext/priv-app/XShare