#!/bin/bash

rm -rf $1/product/app/CalendarGoogle
rm -rf $1/product/app/GoogleContacts
rm -rf $1/product/app/GoogleOne
rm -rf $1/recovery-from-boot.p
rm -rf $1/product/priv-app/Wellbeing
rm -rf $1/priv-app/Turbo
rm -rf $1/priv-app/YellowPage
rm -rf $1/priv-app/facebook-installer
rm -rf $1/priv-app/facebook-services
rm -rf $1/app/Lens
rm -rf $1/product/priv-app/Velvet
rm -rf $1/product/priv-app/AndroidAutoStub
rm -rf $1/product/priv-app/HotwordEnrollmentOKGoogleHEXAGON
rm -rf $1/product/priv-app/Turbo
rm -rf $1/product/priv-app/HotwordEnrollmentXGoogleHEXAGON
rm -rf $1/product/app/Gmail2
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/Maps
rm -rf $1/product/app/YouTube
rm -rf $1/priv-app/Maps
rm -rf $1/priv-app/Velvet
rm -rf $1/app/YouTube
rm -rf $1/app/Photos
rm -rf $1/app/Messages
rm -rf $1/app/Drive
rm -rf $1/app/Gmail2
rm -rf $1/app/Translate
rm -rf $1/app/Duo
rm -rf $1/app/Keep
rm -rf $1/app/GoogleTTS
rm -rf $1/app/talkback
rm -rf $1/app/Maps
