#!/bin/bash

systempath=$1
thispath=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

rm -rf $1/app/Mipay
rm -rf $1/app/MiuiDaemon
rm -rf $1/app/KSICibaEngine
rm -rf $1/app/MiuiSuperMarket
rm -rf $1/app/MiuiVideoGlobal
rm -rf $1/app/Joyose
rm -rf $1/app/Updater
rm -rf $1/app/NextPay
rm -rf $1/app/Lens
rm -rf $1/app/Notes
rm -rf $1/app/MiDrive
rm -rf $1/app/PaymentService
rm -rf $1/app/CtsShimPrebuilt
rm -rf $1/app/XiaomiServiceFramework
rm -rf $1/app/XiaomiSimActivateService
rm -rf $1/app/MiRadio
rm -rf $1/app/cit
rm -rf $1/app/Email
rm -rf $1/app/MiuiBugReport
rm -rf $1/app/MiuiCompass
rm -rf $1/priv-app/Browser
rm -rf $1/priv-app/MiShare
rm -rf $1/priv-app/MiuiScanner
rm -rf $1/priv-app/Provision
rm -rf $1/priv-app/YellowPage
rm -rf $1/priv-app/MiuiVideo
rm -rf $1/priv-app/Music
rm -rf $1/priv-app/MiBrowserGlobal
rm -rf $1/priv-app/MiMover
rm -rf $1/product/app/GoogleTTS
rm -rf $1/product/app/talkback
rm -rf $1/product/priv-app/Velvet
rm -rf $1/data-app/MiRadio
rm -rf $1/data-app/com.baidu.haokan
rm -rf $1/data-app/com.taobao.taobao_24
rm -rf $1/data-app/Notes
rm -rf $1/data-app/com.eg.android.AlipayGphone_23
rm -rf $1/data-app/com.xunmeng.pinduoduo_19
rm -rf $1/data-app/com.sina.weibo_16
rm -rf $1/data-app/MiShop
rm -rf $1/data-app/XiaoAiSpeechEngine
rm -rf $1/data-app/Email
rm -rf $1/data-app/BaiduIME
rm -rf $1/data-app/MiFinance
rm -rf $1/data-app/MiuiScanner
rm -rf $1/data-app/MiuiCompass
rm -rf $1/data-app/Userguide
rm -rf $1/data-app/Huanji
rm -rf $1/data-app/VirtualSim
rm -rf $1/data-app/VipAccount
rm -rf $1/data-app/com.sina.weibo
rm -rf $1/data-app/com.taobao.taobao
rm -rf $1/data-app/Youpin
rm -rf $1/data-app/com.baidu.haokan
rm -rf $1/data-app/XMRemoteController
rm -rf $1/data-app/com.moji.mjweather
rm -rf $1/data-app/com.xunmeng.pinduoduo
rm -rf $1/data-app/MiLiveAssistant
rm -rf $1/data-app/MiuiDriveMode
rm -rf $1/data-app/MiMobileNoti
rm -rf $1/data-app/XiaomiJrSecurity
rm -rf $1/data-app/XMPass
rm -rf $1/data-app/SmartTravel
rm -rf $1/data-app/MiDrive
rm -rf $1/data-app/com.eg.android.AlipayGphone
rm -rf $1/data-app/MiCreditInStub
