#!/bin/bash

systempath=$1
thispath=`cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd`

rm -rf $1/MzApp/ARruler
rm -rf $1/MzApp/Calculator
rm -rf $1/MzApp/DsGame
rm -rf $1/MzApp/Email
rm -rf $1/MzApp/FlymeCalendar
rm -rf $1/MzApp/Game*
rm -rf $1/MzApp/Life
rm -rf $1/MzApp/MzStore
rm -rf $1/MzApp/NotePaper
rm -rf $1/MzApp/Pedometer
rm -rf $1/MzApp/Reader
rm -rf $1/MzApp/TodoList
rm -rf $1/MzApp/VideoClips
rm -rf $1/MzApp/Weather
rm -rf $1/app/AlwaysOnDisplay
rm -rf $1/app/AppCenter
rm -rf $1/app/AppCenterIntl
rm -rf $1/app/BasicDreams
rm -rf $1/app/Bridge
rm -rf $1/app/Calculator
rm -rf $1/app/CalendarGoogle
rm -rf $1/app/Camera
rm -rf $1/app/CameraTest
rm -rf $1/app/CosMaster
rm -rf $1/app/Drive
rm -rf $1/app/Duo
rm -rf $1/app/FileManager
rm -rf $1/app/FlymeAlarmClock
rm -rf $1/app/Gmail2
rm -rf $1/app/GooglePay
rm -rf $1/app/GoogleTTS
rm -rf $1/app/IntlNews
rm -rf $1/app/Maps
rm -rf $1/app/Music
rm -rf $1/app/Music2
rm -rf $1/app/MzCloudService
rm -rf $1/app/MzPay
rm -rf $1/app/MzSecurity
rm -rf $1/app/MzShare
rm -rf $1/app/MzSyncService
rm -rf $1/app/MzUCService
rm -rf $1/app/MzUpdate*
rm -rf $1/app/NotePaper
rm -rf $1/app/PaymentService
rm -rf $1/app/Photos
rm -rf $1/app/Protips
rm -rf $1/app/Updater
rm -rf $1/app/Videos
rm -rf $1/app/YouTube
rm -rf $1/app/alphame
rm -rf $1/app/assistans
rm -rf $1/app/calculator
rm -rf $1/app/callsetting
rm -rf $1/app/camera
rm -rf $1/app/dsgame
rm -rf $1/app/filemanager
rm -rf $1/app/flymelab
rm -rf $1/app/gallery
rm -rf $1/app/gamecenter
rm -rf $1/app/mcare
rm -rf $1/app/mstore
rm -rf $1/app/mznfcpay
rm -rf $1/app/notepaper
rm -rf $1/app/pay
rm -rf $1/app/pedometer
rm -rf $1/app/picker
rm -rf $1/app/safe
rm -rf $1/app/suggestion
rm -rf $1/app/talkback
rm -rf $1/customizecenter/wallpapers/2a.png
rm -rf $1/customizecenter/wallpapers/2a_thumb.png
rm -rf $1/customizecenter/wallpapers/3a.png
rm -rf $1/customizecenter/wallpapers/3a_thumb.png
rm -rf $1/customizecenter/wallpapers/4a.png
rm -rf $1/customizecenter/wallpapers/4a_thumb.png
rm -rf $1/customizecenter/wallpapers/5a.png
rm -rf $1/customizecenter/wallpapers/5a_thumb.png
rm -rf $1/customizecenter/wallpapers/a.jpg
rm -rf $1/customizecenter/wallpapers/a_thumb.jpg
rm -rf $1/customizecenter/wallpapers/b.jpg
rm -rf $1/customizecenter/wallpapers/b_thumb.jpg
rm -rf $1/customizecenter/wallpapers/bb.jpg
rm -rf $1/customizecenter/wallpapers/bb_thumb.jpg
rm -rf $1/customizecenter/wallpapers/e.png
rm -rf $1/customizecenter/wallpapers/e_thumb.jpg
rm -rf $1/customizecenter/wallpapers/ee.jpg
rm -rf $1/customizecenter/wallpapers/ee_thumb.jpg
rm -rf $1/customizecenter/wallpapers/eee.jpg
rm -rf $1/customizecenter/wallpapers/eee_thumb.jpg
rm -rf $1/customizecenter/wallpapers/f.png
rm -rf $1/customizecenter/wallpapers/f_thumb.jpg
rm -rf $1/customizecenter/wallpapers/ff.jpg
rm -rf $1/customizecenter/wallpapers/ff_thumb.jpg
rm -rf $1/customizecenter/wallpapers/fff.jpg
rm -rf $1/customizecenter/wallpapers/fff_thumb.jpg
rm -rf $1/customizecenter/wallpapers/g.png
rm -rf $1/customizecenter/wallpapers/g_thumb.jpg
rm -rf $1/customizecenter/wallpapers/gg.jpg
rm -rf $1/customizecenter/wallpapers/gg_thumb.jpg
rm -rf $1/customizecenter/wallpapers/ggg.jpg
rm -rf $1/customizecenter/wallpapers/ggg_thumb.jpg
rm -rf $1/customizecenter/wallpapers/h.png
rm -rf $1/customizecenter/wallpapers/h_thumb.png
rm -rf $1/customizecenter/wallpapers/i.png
rm -rf $1/customizecenter/wallpapers/i_thumb.png
rm -rf $1/customizecenter/wallpapers/j.png
rm -rf $1/customizecenter/wallpapers/j_thumb.png
rm -rf $1/customizecenter/wallpapers/k.png
rm -rf $1/customizecenter/wallpapers/k_thumb.png
rm -rf $1/customizecenter/wallpapers/l.png
rm -rf $1/customizecenter/wallpapers/l_thumb.png
rm -rf $1/customizecenter/wallpapers/m.png
rm -rf $1/customizecenter/wallpapers/m_thumb.png
rm -rf $1/customizecenter/wallpapers/o.png
rm -rf $1/customizecenter/wallpapers/o_thumb.png
rm -rf $1/customizecenter/wallpapers/p.png
rm -rf $1/customizecenter/wallpapers/p_thumb.png
rm -rf $1/customizecenter/wallpapers/q.png
rm -rf $1/customizecenter/wallpapers/q_thumb.png
rm -rf $1/customizecenter/wallpapers/r.png
rm -rf $1/customizecenter/wallpapers/r_thumb.png
rm -rf $1/priv-app/ActivatePhone
rm -rf $1/priv-app/AlphaMe
rm -rf $1/priv-app/Assistant
rm -rf $1/priv-app/Backup
rm -rf $1/priv-app/Browser
rm -rf $1/priv-app/Calculator
rm -rf $1/priv-app/Calendar
rm -rf $1/priv-app/Email
rm -rf $1/priv-app/Feedback
rm -rf $1/priv-app/FlymeGallery
rm -rf $1/priv-app/FlymeMusic
rm -rf $1/priv-app/FlymeSoundRecorder
rm -rf $1/priv-app/MeizuPay
rm -rf $1/priv-app/Music
rm -rf $1/priv-app/MzSetupWizard
rm -rf $1/priv-app/Search
rm -rf $1/priv-app/SoundRecorder
rm -rf $1/priv-app/Suggestion
rm -rf $1/priv-app/ToolBox
rm -rf $1/priv-app/Turbo
rm -rf $1/priv-app/Velvet
rm -rf $1/priv-app/Video
rm -rf $1/priv-app/VoiceAssistant
rm -rf $1/priv-app/assistans
rm -rf $1/priv-app/calculator
rm -rf $1/priv-app/callsetting
rm -rf $1/priv-app/camera
rm -rf $1/priv-app/dsgame
rm -rf $1/priv-app/filemanager
rm -rf $1/priv-app/flymelab
rm -rf $1/priv-app/gallery
rm -rf $1/priv-app/gamecenter
rm -rf $1/priv-app/mcare
rm -rf $1/priv-app/mstore
rm -rf $1/priv-app/mznfcpay
rm -rf $1/priv-app/notepaper
rm -rf $1/priv-app/pay
rm -rf $1/priv-app/pedometer
rm -rf $1/priv-app/picker
rm -rf $1/priv-app/safe
rm -rf $1/priv-app/suggestion
rm -rf $1/priv-app/wt_logcat
rm -rf $1/product/app/MarkupGoogle
rm -rf $1/product/app/talkback
